### ISSUE TITLE
这个目前已经失效了吧？

### ISSUE THREAD

**Issue by 1558204459** [wangzhenjjcn/FuYiSpider#1]

**Comment by wangzhenjjcn** [comment]
it works
 any problem please give me a new issues

Martin Lee <notifications@github.com> 于2018年8月24日周五 下午5:05写道：

**Comment by 1558204459** [comment]
Only 10 pages of area’s data were shown in this website
How does your program grab the other 10 pages’ data?
Have you ever checked this website recently?

**Comment by wangzhenjjcn** [comment]
@1558204459 like code  for n in range(0,49):
49 is the pages size
and you can read it from first page content or just edit the number if you just wanna read one or two city data

**Comment by wangzhenjjcn** [comment]
@1558204459 
I found that
start page changed to this:
http://www.poi86.com/poi/amap/city/320500.html

**Comment by 1558204459** [comment]
It’s ok
I Just found your spider,your program is good

**Comment by wangzhenjjcn** [comment]
I wanna close this issue
